// Do not edit this file!
#include <iostream>
#include <iomanip>
#include "Cafe.h"
using namespace std;

int main() {
	// Variables
	int choice, quantity;
	float total = 0.0;
	bool break_out = false;

	do {
		// Clear the screen
		system("cls");

		cout << "Welcome to The Turring Cafe" << endl
			 << "Please select from the following options:" << endl;

		displayMenu();
		cin >> choice;

		if (choice != 5) {
			cout << "How many? ";
			cin >> quantity;

			switch(choice)
			{
				case 1:
					total += calcOrder("Hotdog", 1.50, quantity);
                    break;
				case 2:
					total += calcOrder("Popcorn", 3.10, quantity);
                    break;
				case 3:
					total += calcOrder("Hot Chocolate", 2.69, quantity);
                    break;
				case 4:
					total += calcOrder("Soft Drink", 1.25, quantity);
                    break;
			}
		}

		calcTotal(total);

	} while(choice != 5);

	cout << "Goodbye!" << endl;

	return 0;
}
