// Do not edit this file!
#include <assert.h>
#include "palindrome.h"

int main() {
	// These should all return true
	assert(isPalindrome("abba"));
	assert(isPalindrome("abbcbba"));
	assert(isPalindrome("racecar"));
	assert(isPalindrome("tacocat"));
	assert(isPalindrome("noxinnixon"));
	assert(isPalindrome("amanaplanacanalpanama"));
	assert(isPalindrome("wasitacaroracatisaw"));

	// These should return false
	assert(!isPalindrome("aazz"));
	assert(!isPalindrome("myname"));
	assert(!isPalindrome("wasd"));
	assert(!isPalindrome("noreasontogetexcited"));
	assert(!isPalindrome("thetheifhekindlyspoke"));

	return 0;
}
